spring:
    application:
      name:mood

    # DataSource Config
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/moodmessage
        username: root
        password: 123456
    #session失效时间
    session:
        timeout: 86400
        store-type: redis
    # redis 配置
    data:
        redis:
            port: 6379
            host: localhost
            database: 1
server:
    port: 8080
    servlet:
        context-path: /api
        session:
            cookie:
                domain: localhost
mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: is_deleted # 全局逻辑删除字段名
            logic-delete-value: 1 # 逻辑已删除值
            logic-not-delete-value: 0 # 逻辑未删除值

knife4j:
    enable: true
    openapi:
        title: Knife4j
        description: 情绪管理系统
    # aaa"
        email: 1651299287@qq.com
        concat: 吴铭稞
        url:
        version: v1.0
        license: Apache 2.0
        license-url: https://stackoverflow.com/
        terms-of-service-url: https://stackoverflow.com/
        group:
            test1:
                group-name: 分组名称
                api-rule: package
                api-rule-resources:
                    - com.wmk.mood.controller